"""Upgrade

Revision ID: 03060d0e9d4d
Revises: d4ca5533a5e5
Create Date: 2024-11-20 08:41:06.178585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03060d0e9d4d'
down_revision: Union[str, None] = 'd4ca5533a5e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'description')
    op.add_column('clients', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('clients', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('clients', 'is_active')
    op.add_column('admins', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
