"""Create clients table

Revision ID: 094e0d6a38e4
Revises: 1ed7e91be38c
Create Date: 2024-11-19 19:57:19.504248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '094e0d6a38e4'
down_revision: Union[str, None] = '1ed7e91be38c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
