"""Upgrade_v4

Revision ID: 923573bddead
Revises: 4876cb7edae9
Create Date: 2024-11-22 00:09:27.283811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '923573bddead'
down_revision: Union[str, None] = '4876cb7edae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('admins', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
