"""Upgrade_v3

Revision ID: a7e53b5df83a
Revises: 4876cb7edae9
Create Date: 2024-11-20 14:17:41.700886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e53b5df83a'
down_revision: Union[str, None] = '4876cb7edae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('username', sa.String(), nullable=False))
    op.drop_column('admins', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admins', 'username')
    # ### end Alembic commands ###
